Revert "Shut up missing openlog/closelog/syslog symbols warnings. Fixes #1"
It was causing the following error when using recent version of
emscripten. Here is the error reported when using v1.36.14

  error: Linking globals named 'closelog': symbol multiply defined!

This reverts commit 652d38537467da674c8d011c9568ce149e6caf0e.